image: sbtscala/scala-sbt:eclipse-temurin-jammy-21.0.2_13_1.10.1_2.13.14

stages:
  - build
  - test

variables:
  SBT_OPTS: "-Xmx1G"

before_script:
  - sbt clean update

build:
  stage: build
  script:
    - sbt "scalafmtCheckAll; compile"

test:
  stage: test
  script:
    - sbt test

